title: Paris Kasidiaris
email: paris@sourcelair.com
description: >
  Personal blog of Paris Kasidiaris, co-founder at SourceLair.
  I keep different usernames in online services. It sucks, I know it.
baseurl: ""
url: "http://www.pkasid.com"
twitter_username: pariskasid
github_username:  parisk

markdown: kramdown
