title: Paris Kasidiaris
email: paris@sourcelair.com
description: >
  Personal blog of Paris Kasidiaris, co-founder at SourceLair.
baseurl: ""
url: "http://www.pkasid.com"
twitter_username: pariskasid
github_username:  parisk

markdown: kramdown

collections:
  archive:
    permalink: /archive/:path/
    output: true

gems:
  - jekyll-redirect-from
