title: Paris Kasidiaris
email: paris@sourcelair.com
description: >
  Personal blog of Paris Kasidiaris, co-founder at sourcelair.com.
  I do not keep the same username in any online service. It sucks, I know it.
baseurl: ""
url: "http://www.pkasid.com"
twitter_username: pariskasid
github_username:  parisk

markdown: kramdown
